ENV['RCT_NEW_ARCH_ENABLED'] = '1'

# Resolve react_native_pods.rb with node to allow for hoisting
require_relative '../node_modules/react-native/scripts/react_native_pods.rb'

platform :ios, '15.1'
prepare_react_native_project!

project 'SoundExample.xcodeproj'

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'SoundExample' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false,
      # :ccache_enabled => true
    )
    
    # Disable warnings for pods
    installer.pods_project.targets.each do |target|
      target.build_configurations.each do |config|
        # Disable all warnings from pods
        config.build_settings['GCC_WARN_INHIBIT_ALL_WARNINGS'] = 'YES'
        # Disable specific documentation warnings
        config.build_settings['CLANG_WARN_DOCUMENTATION_COMMENTS'] = 'NO'
      end
    end

    # Patch RN Codegen script phase to use stable relative paths (fixes xcodebuild 65)
    installer.pods_project.targets.each do |t|
      t.build_phases.each do |phase|
        next unless phase.respond_to?(:name) && phase.respond_to?(:shell_script)
        name = phase.name.to_s
        script = phase.shell_script.to_s
        if name.include?('Generate Specs') || script.include?('RCT_SCRIPT_RN_DIR')
          phase.shell_script = <<-'SCRIPT'
pushd "$PODS_ROOT/../" > /dev/null
RCT_SCRIPT_POD_INSTALLATION_ROOT=$(pwd)
popd >/dev/null

export RCT_SCRIPT_RN_DIR="$PODS_ROOT/../../node_modules/react-native"
export RCT_SCRIPT_APP_PATH="$PODS_ROOT/../../"
export RCT_SCRIPT_OUTPUT_DIR="$RCT_SCRIPT_POD_INSTALLATION_ROOT"
export RCT_SCRIPT_TYPE="withCodegenDiscovery"

export SCRIPT_PHASES_SCRIPT="$RCT_SCRIPT_RN_DIR/scripts/react_native_pods_utils/script_phases.sh"
export WITH_ENVIRONMENT="$RCT_SCRIPT_RN_DIR/scripts/xcode/with-environment.sh"
/bin/sh -c '"$WITH_ENVIRONMENT" "$SCRIPT_PHASES_SCRIPT"'
SCRIPT
        end
      end
    end
  end
end
